name: Deploy to EC2 (Manual Setup)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.202.214.73 << 'EOF'
          cd ~/NoteAppBackend || exit
          git pull origin main || exit
          pip install -r requirements.txt || exit
          sudo supervisorctl restart guni:gunicorn || exit
          sudo systemctl restart nginx || exit
        EOF

